const form=document.getElementById('news-admin-form');
const title=document.getElementById('admin-title');
const date=document.getElementById('admin-date');
const category=document.getElementById('admin-category');
const team=document.getElementById('admin-team');
const summary=document.getElementById('admin-summary');
const lead=document.getElementById('admin-lead');
const body=document.getElementById('admin-body');
const preview=document.getElementById('admin-preview');
const publishActions=document.getElementById('admin-publish-actions');
const downloadBtn=document.getElementById('admin-download');
const copyBtn=document.getElementById('admin-copy');
const resetBtn=document.getElementById('admin-reset');
const status=document.getElementById('admin-status');
const count=document.getElementById('admin-existing-count');
let currentNews={updated_at:'',articles:[]};
let generatedNews=null;
let editingId=null;

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={club:'Club News',match:'Match Report',community:'Community',juniors:'Juniors',women:'Women & Girls',event:'Events'};
function slugify(value){return String(value||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||`news-${Date.now()}`;}
function defaultLinks(cat){if(cat==='match')return[{label:'Fixtures & results',href:'fixtures.html'},{label:'Player statistics',href:'honours.html'}];if(cat==='juniors')return[{label:'Junior cricket',href:'juniors.html'},{label:'Contact the club',href:'join.html'}];if(cat==='women')return[{label:'Women’s cricket',href:'team-women.html'},{label:'Contact the club',href:'join.html'}];return[{label:'More club news',href:'news.html'},{label:'Contact the club',href:'join.html'}];}
function paragraphs(value){return String(value||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);}
function formatDate(value){if(!value)return'';const d=new Date(`${value}T12:00:00`);return d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});}
function buildArticle(){const existing=editingId?(currentNews.articles||[]).find(a=>a.id===editingId):null;const article={id:editingId||slugify(title.value),title:title.value.trim(),date:date.value,category:category.value,category_label:labels[category.value]||'Club News'};if(team.value.trim())article.team=team.value.trim();article.summary=summary.value.trim();article.lead=lead.value.trim();article.body=paragraphs(body.value);article.links=existing?.links||defaultLinks(category.value);return article;}
function makeUniqueId(article){if(editingId)return article.id;const ids=new Set((currentNews.articles||[]).map(a=>a.id));if(!ids.has(article.id))return article.id;let i=2;while(ids.has(`${article.id}-${i}`))i++;return `${article.id}-${i}`;}
function renderPreview(article){preview.innerHTML=`<article class="admin-story-preview"><div class="admin-story-meta"><span class="tag">${esc(article.category_label)}</span><span>${esc(formatDate(article.date))}</span>${article.team?`<span>${esc(article.team)}</span>`:''}</div><h3>${esc(article.title)}</h3><p class="admin-story-summary">${esc(article.summary)}</p><p class="admin-story-lead">${esc(article.lead)}</p>${article.body.map(p=>`<p>${esc(p)}</p>`).join('')}<p><a class="text-link" href="article.html?id=${encodeURIComponent(article.id)}">Article link →</a></p></article>`;}
function updatedPayload(articles){return{updated_at:new Date().toISOString().slice(0,10),articles};}
function setPublishReady(message){publishActions.hidden=false;status.textContent=message;}
function resetEditor(){editingId=null;form.reset();date.value=new Date().toISOString().slice(0,10);preview.innerHTML='<p>Complete the form and choose <strong>Preview story</strong>.</p>';publishActions.hidden=true;generatedNews=null;status.textContent='';const submit=form.querySelector('button[type="submit"]');if(submit)submit.textContent='Preview story';title.focus();}
function populateEditor(article){editingId=article.id;title.value=article.title||'';date.value=article.date||'';category.value=article.category||'club';team.value=article.team||'';summary.value=article.summary||'';lead.value=article.lead||'';body.value=(article.body||[]).join('\n\n');const submit=form.querySelector('button[type="submit"]');if(submit)submit.textContent='Preview changes';renderPreview(article);publishActions.hidden=true;status.textContent=`Editing: ${article.title}`;form.scrollIntoView({behavior:'smooth',block:'start'});}
function ensureManager(){if(document.getElementById('admin-existing-news'))return;const previewSection=preview?.closest('.section');if(!previewSection)return;const section=document.createElement('section');section.className='section section-alt admin-manage-section';section.innerHTML='<div class="container"><div class="section-heading"><div><p class="eyebrow dark">Current stories</p><h2>Edit or delete news</h2></div></div><div id="admin-existing-news" class="admin-existing-news"><p>Loading stories…</p></div></div>';previewSection.parentNode.insertBefore(section,previewSection);}
function renderManager(){ensureManager();const box=document.getElementById('admin-existing-news');if(!box)return;const articles=currentNews.articles||[];if(!articles.length){box.innerHTML='<p>No news stories found.</p>';return;}box.innerHTML=articles.map(a=>`<article class="admin-news-row" data-id="${esc(a.id)}"><div><span class="tag">${esc(a.category_label||labels[a.category]||'News')}</span><h3>${esc(a.title)}</h3><p>${esc(formatDate(a.date))}${a.team?' · '+esc(a.team):''}</p></div><div class="admin-news-row-actions"><button class="btn btn-outline dark-outline admin-edit-news" type="button" data-id="${esc(a.id)}">Edit</button><button class="btn admin-delete-news" type="button" data-id="${esc(a.id)}">Delete</button></div></article>`).join('');box.querySelectorAll('.admin-edit-news').forEach(btn=>btn.addEventListener('click',()=>{const article=articles.find(a=>a.id===btn.dataset.id);if(article)populateEditor(article);}));box.querySelectorAll('.admin-delete-news').forEach(btn=>btn.addEventListener('click',()=>{const article=articles.find(a=>a.id===btn.dataset.id);if(!article)return;if(!confirm(`Delete “${article.title}”?\n\nNothing is published until you copy the updated JSON to GitHub.`))return;generatedNews=updatedPayload(articles.filter(a=>a.id!==article.id));preview.innerHTML=`<article class="admin-story-preview"><span class="tag">Delete</span><h3>${esc(article.title)}</h3><p>This story will be removed from the news file when you publish the updated JSON.</p></article>`;setPublishReady('Delete ready. Copy the updated JSON and commit it in GitHub.');editingId=null;}));}
async function loadNews(){try{const res=await fetch(`data/news.json?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error();currentNews=await res.json();count.textContent=`${(currentNews.articles||[]).length} existing stor${(currentNews.articles||[]).length===1?'y':'ies'} loaded.`;renderManager();}catch(e){count.textContent='Could not load current news. Do not publish until the existing file is available.';currentNews={updated_at:'',articles:[]};renderManager();}}
form?.addEventListener('submit',e=>{e.preventDefault();const article=buildArticle();article.id=makeUniqueId(article);if(editingId){const articles=(currentNews.articles||[]).map(a=>a.id===editingId?article:a);generatedNews=updatedPayload(articles);renderPreview(article);setPublishReady('Changes ready. Copy the updated JSON and commit it in GitHub.');}else{generatedNews=updatedPayload([article,...(currentNews.articles||[])]);renderPreview(article);setPublishReady('New story ready. Copy the updated JSON and commit it in GitHub.');}});
downloadBtn?.addEventListener('click',()=>{if(!generatedNews)return;const blob=new Blob([JSON.stringify(generatedNews,null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='news.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);status.textContent='news.json downloaded.';});
copyBtn?.addEventListener('click',async()=>{if(!generatedNews)return;try{await navigator.clipboard.writeText(JSON.stringify(generatedNews,null,2)+'\n');status.textContent='JSON copied to clipboard. Now open news.json on GitHub, edit, paste and commit.';}catch(e){status.textContent='Clipboard access was blocked. Use Download instead.';}});
resetBtn?.addEventListener('click',resetEditor);
if(date&&!date.value)date.value=new Date().toISOString().slice(0,10);
ensureManager();
loadNews();