import { readCookie, verifySession } from '../lib/session.js';
const OWNER='fauxy87',REPO='sutton-cricket-club',BRANCH='main',PATH='data/sponsors.json';
function headers(){const token=process.env.GITHUB_PUBLISH_TOKEN;if(!token)throw new Error('GITHUB_PUBLISH_TOKEN is not configured');return {'Authorization':`Bearer ${token}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'};}
async function getFile(){const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PATH}?ref=${BRANCH}`,{headers:headers()});if(!r.ok)throw new Error(`Could not read sponsors (${r.status})`);const f=await r.json();return{sha:f.sha,data:JSON.parse(Buffer.from(f.content,'base64').toString('utf8'))};}
async function putFile(sha,data,message){const body={message,branch:BRANCH,sha,content:Buffer.from(JSON.stringify(data,null,2)+'\n').toString('base64')};const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PATH}`,{method:'PUT',headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(`Could not publish sponsors (${r.status})`);}
async function putAsset(path,content,message){const url=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`;let sha;const old=await fetch(`${url}?ref=${BRANCH}`,{headers:headers()});if(old.ok)sha=(await old.json()).sha;const body={message,branch:BRANCH,content,...(sha?{sha}:{})};const r=await fetch(url,{method:'PUT',headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(`Could not upload logo (${r.status})`);}
function clean(v,n=1000){return String(v??'').trim().slice(0,n)}
function slug(v){return clean(v,100).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`sponsor-${Date.now()}`}
function year(v,fallback){const n=Number(v);return Number.isInteger(n)&&n>=1877&&n<=2200?n:fallback}
function normalise(raw,existing={}){const id=clean(raw.id,100)||existing.id||`sponsor-${Date.now()}`;const allowed=['Main sponsor','Colts sponsor','Banner sponsor','Club supporter'];const type=allowed.includes(raw.type)?raw.type:'Club supporter';const currentYear=new Date().getUTCFullYear();const status=['active','previous'].includes(raw.status)?raw.status:(existing.status||'active');const start=year(raw.season_start,year(existing.season_start,currentYear));const end=year(raw.season_end,year(existing.season_end,start));return{id,name:clean(raw.name,120),type,status,season_start:start,season_end:Math.max(start,end),website:clean(raw.website,500),logo:clean(raw.logo,1000),logo_alt:clean(raw.logo_alt,160)||`${clean(raw.name,120)} logo`,description:clean(raw.description,700),testimonial:clean(raw.testimonial,900),testimonial_name:clean(raw.testimonial_name,120),testimonial_role:clean(raw.testimonial_role,160),show_testimonial:raw.show_testimonial===true||raw.show_testimonial==='true',order:Math.max(1,Number(raw.order)||999)};}
export default async function handler(req,res){if(!verifySession(readCookie(req)))return res.status(401).json({ok:false,error:'Not signed in'});res.setHeader('Cache-Control','no-store');try{const file=await getFile(),data=file.data||{},items=Array.isArray(data.sponsors)?data.sponsors:[];if(req.method==='GET')return res.status(200).json({ok:true,sponsors:items});if(req.method!=='POST')return res.status(405).json({ok:false,error:'Method not allowed'});const body=req.body||{};if(body.action==='delete'){const id=clean(body.id,100),next=items.filter(x=>x.id!==id);if(next.length===items.length)return res.status(404).json({ok:false,error:'Sponsor not found'});await putFile(file.sha,{...data,updated_at:new Date().toISOString().slice(0,10),sponsors:next},'Delete website sponsor');return res.status(200).json({ok:true,message:'Sponsor deleted'});}if(body.action==='save'){const id=clean(body.sponsor?.id,100),index=id?items.findIndex(x=>x.id===id):-1,existing=index>=0?items[index]:{},raw={...(body.sponsor||{})};if(body.logo?.data){const match=String(body.logo.data).match(/^data:image\/(png|jpeg|webp);base64,(.+)$/);if(!match)throw new Error('Logo must be a PNG, JPG or WebP image');const ext=match[1]==='jpeg'?'jpg':match[1],path=`assets/sponsors/${slug(raw.name||existing.name)}.${ext}`;await putAsset(path,match[2],`Upload sponsor logo for ${clean(raw.name||existing.name,120)}`);raw.logo=path;}const item=normalise(raw,existing);if(!item.name)return res.status(400).json({ok:false,error:'Sponsor name is required'});const next=items.slice();if(index>=0)next[index]=item;else next.push(item);await putFile(file.sha,{...data,updated_at:new Date().toISOString().slice(0,10),sponsors:next},index>=0?'Update website sponsor':'Add website sponsor');return res.status(200).json({ok:true,sponsor:item,message:index>=0?'Sponsor updated':'Sponsor added'});}return res.status(400).json({ok:false,error:'Unknown action'});}catch(err){return res.status(500).json({ok:false,error:err.message||'Sponsor update failed'});}}
