import { readCookie, verifySession } from '../lib/session.js';
const OWNER='fauxy87',REPO='sutton-cricket-club',BRANCH='main',PATH='data/weekly-draw.json';
function headers(){const token=process.env.GITHUB_PUBLISH_TOKEN;if(!token)throw new Error('GITHUB_PUBLISH_TOKEN is not configured');return {'Authorization':`Bearer ${token}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'};}
async function getFile(){const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PATH}?ref=${BRANCH}`,{headers:headers()});if(!r.ok)throw new Error(`Could not read draw data (${r.status})`);const f=await r.json();return{sha:f.sha,data:JSON.parse(Buffer.from(f.content,'base64').toString('utf8'))};}
async function putFile(sha,data,message){const body={message,branch:BRANCH,sha,content:Buffer.from(JSON.stringify(data,null,2)+'\n').toString('base64')};const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${PATH}`,{method:'PUT',headers:headers(),body:JSON.stringify(body)});if(!r.ok)throw new Error(`Could not publish draw data (${r.status})`);}
const clean=(v,n=160)=>String(v??'').trim().slice(0,n);
function normalise(x){return{id:clean(x.id,100)||`draw-${Date.now()}`,date:clean(x.date,10),label:clean(x.label,80),first_number:clean(x.first_number,20),first_name:clean(x.first_name),first_prize:Math.max(0,Number(x.first_prize)||15),second_number:clean(x.second_number,20),second_name:clean(x.second_name),second_prize:Math.max(0,Number(x.second_prize)||5)};}
function normaliseTicket(x){return{id:clean(x.id,100)||`ticket-${Date.now()}`,number:clean(x.number,20),name:clean(x.name,160),note:clean(x.note,240)};}
export default async function handler(req,res){if(!verifySession(readCookie(req)))return res.status(401).json({ok:false,error:'Not signed in'});res.setHeader('Cache-Control','no-store');try{const file=await getFile(),data=file.data||{},items=Array.isArray(data.results)?data.results:[],tickets=Array.isArray(data.tickets)?data.tickets:[];if(req.method==='GET')return res.status(200).json({ok:true,season:data.season||2026,results:items,tickets});if(req.method!=='POST')return res.status(405).json({ok:false,error:'Method not allowed'});const b=req.body||{};
if(b.action==='delete-ticket'){const next=tickets.filter(x=>x.id!==clean(b.id,100));await putFile(file.sha,{...data,updated_at:new Date().toISOString().slice(0,10),tickets:next,results:items},'Delete Weekly Draw ticket');return res.status(200).json({ok:true,message:'Ticket allocation deleted'});}
if(b.action==='save-ticket'){const ticket=normaliseTicket(b.ticket||{});if(!ticket.number||!ticket.name)return res.status(400).json({ok:false,error:'Ticket number and name are required'});const duplicate=tickets.find(x=>String(x.number).trim().toLowerCase()===ticket.number.toLowerCase()&&x.id!==ticket.id);if(duplicate)return res.status(400).json({ok:false,error:`Number ${ticket.number} is already allocated to ${duplicate.name}`});const index=tickets.findIndex(x=>x.id===ticket.id),next=tickets.slice();if(index>=0)next[index]=ticket;else next.push(ticket);await putFile(file.sha,{...data,updated_at:new Date().toISOString().slice(0,10),tickets:next,results:items},index>=0?'Update Weekly Draw ticket':'Allocate Weekly Draw ticket');return res.status(200).json({ok:true,ticket,message:index>=0?'Ticket allocation updated':'Ticket number allocated'});}
if(b.action==='delete'){const next=items.filter(x=>x.id!==clean(b.id,100));await putFile(file.sha,{...data,updated_at:new Date().toISOString().slice(0,10),tickets,results:next},'Delete Weekly Draw result');return res.status(200).json({ok:true,message:'Draw result deleted'});}
if(b.action==='save'){const item=normalise(b.result||{});if(!item.date||!item.first_number||!item.second_number)return res.status(400).json({ok:false,error:'Date and both winning numbers are required'});const owner=n=>tickets.find(t=>String(t.number).trim().toLowerCase()===String(n).trim().toLowerCase());if(!item.first_name)item.first_name=owner(item.first_number)?.name||'';if(!item.second_name)item.second_name=owner(item.second_number)?.name||'';const index=items.findIndex(x=>x.id===item.id),next=items.slice();if(index>=0)next[index]=item;else next.push(item);await putFile(file.sha,{...data,updated_at:new Date().toISOString().slice(0,10),tickets,results:next},index>=0?'Update Weekly Draw result':'Add Weekly Draw result');return res.status(200).json({ok:true,result:item,message:index>=0?'Draw result updated':'Draw result published'});}return res.status(400).json({ok:false,error:'Unknown action'});}catch(e){return res.status(500).json({ok:false,error:e.message||'Weekly Draw update failed'});}}
